#!/usr/bin/env python3
"""Generate the synthetic UI acceptance workspace; no Desktop/Fabric is needed.

Usage from a checkout with its Python dependencies installed:
    PYTHONPATH=src python scripts/generate_ui_acceptance_fixture.py /tmp/smc-ui-acceptance
    PYTHONPATH=src python -m semantic_model_cleaner /tmp/smc-ui-acceptance --format json

Select Synthetic Acceptance.SemanticModel and both generated reports in the UI.
Sales has 45 children including report-owned measures. Inspect Revenue's references
and Amount's incoming dependency, DateKey/SortOrder's structural roles, the quoted
and long names, and Safe Cleanup Candidate. Executive owns Revenue vs Target;
promotion requires inclusion of Report Target. Broken Revenue and the diagnostic
visual/obsolete selector supply intentional broken/stale cases.

The output must be absent or empty; existing files and symlinks are refused.
Generated bytes are deterministic. Printed counts come from the real analyzer.
"""
import argparse
from collections import Counter
import json
from pathlib import Path


MODEL = 'Synthetic Acceptance.SemanticModel'
REPORTS = ('Synthetic Executive.Report', 'Synthetic Operations.Report')
LONG_NAME = 'Very long synthetic column name for checking horizontal clipping and complete detail labels'
QUOTED_NAME = "Owner's Region [Synthetic]"
SCHEMA = 'https://developer.microsoft.com/json-schemas/fabric/item/report/'


def _name(value):
    return "'" + value.replace("'", "''") + "'"


def _write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(value, indent=2, ensure_ascii=False) + '\n' if isinstance(value, dict) else value
    with path.open('x', encoding='utf-8', newline='\n') as stream:
        stream.write(text)


def _projection(name, kind='Measure'):
    return {'field': {kind: {'Expression': {'SourceRef': {'Entity': 'Sales'}}, 'Property': name}},
            'queryRef': 'Sales.' + name}


def generate_fixture(output: Path) -> dict:
    output = Path(output)
    if output.is_symlink() or (output.exists() and (not output.is_dir() or any(output.iterdir()))):
        raise ValueError('Output must be a new or empty directory; refusing to modify existing files.')
    output.mkdir(parents=True, exist_ok=output.exists())
    model = output / MODEL
    columns = [
        ('Amount', 'decimal', []), ('DateKey', 'int64', []), ('SortOrder', 'int64', []),
        ('Month Label', 'string', ['sortByColumn: SortOrder']),
        ('Hidden Notes', 'string', ['isHidden']),
        ('Inferred Value', 'int64', ['isNameInferred']),
        (LONG_NAME, 'string', []), (QUOTED_NAME, 'string', []),
    ] + [(f'Synthetic Attribute {number:02d}', 'int64', []) for number in range(1, 30)]
    lines = ['table Sales']
    for name, data_type, properties in columns:
        lines += ['\tcolumn ' + _name(name), '\t\tdataType: ' + data_type,
                  '\t\tsourceColumn: ' + _name(name), *['\t\t' + prop for prop in properties]]
    for name, expression, properties in [
        ('Revenue', 'SUM(Sales[Amount])', ['formatString: #,0.00', 'displayFolder: Performance']),
        ('Safe Cleanup Candidate', '0', ['displayFolder: Cleanup']),
        ('Unused Base', '1', ['displayFolder: Cleanup']),
        ('Unused Derived', '[Unused Base] + 1', ['displayFolder: Cleanup']),
        ('Broken Revenue', '[Missing Revenue] + 1', ['displayFolder: Diagnostics']),
        ('Hidden Forecast', '10', ['isHidden', 'displayFolder: Forecast']),
    ]:
        lines += ['\tmeasure ' + _name(name) + ' = ' + expression,
                  *['\t\t' + prop for prop in properties]]
    column_names = ', '.join(json.dumps(name) for name, _, _ in columns)
    values = ', '.join('"Synthetic"' if data_type == 'string' else '1' for _, data_type, _ in columns)
    lines += ['\tpartition Sales = m', '\t\tmode: import', '\t\tsource =',
              '\t\t\t#table({' + column_names + '}, {{' + values + '}})']
    _write(model / 'definition/tables/Sales.tmdl', '\n'.join(lines) + '\n')
    _write(model / 'definition/tables/Date.tmdl',
           'table Date\n\tcolumn DateKey\n\t\tdataType: int64\n\t\tisKey\n\t\tsourceColumn: DateKey\n'
           '\tcolumn DateLabel\n\t\tdataType: string\n\t\tsourceColumn: DateLabel\n'
           '\tpartition Date = m\n\t\tmode: import\n\t\tsource =\n'
           '\t\t\t#table({"DateKey", "DateLabel"}, {{1, "Synthetic day"}})\n')
    _write(model / 'definition/model.tmdl', 'model Model\n\tculture: en-US\n\nref table Sales\nref table Date\n')
    _write(model / 'definition/relationships.tmdl',
           'relationship SalesDate\n\tfromColumn: Sales.DateKey\n\ttoColumn: Date.DateKey\n'
           '\tfromCardinality: many\n\ttoCardinality: one\n')
    _write(model / 'definition.pbism', {'version': '4.0', 'settings': {}})
    _write(model / '.platform', {'metadata': {'type': 'SemanticModel', 'displayName': 'Synthetic Acceptance'}})
    for report_index, report_name in enumerate(REPORTS):
        report = output / report_name
        _write(report / 'definition.pbir', {'$schema': SCHEMA + 'definitionProperties/2.0.0/schema.json',
               'version': '4.0', 'datasetReference': {'byPath': {'path': '../' + MODEL}}})
        _write(report / 'definition/report.json', {'$schema': SCHEMA + 'definition/report/3.3.0/schema.json',
               'themeCollection': {}})
        for page_index, page_name in enumerate(('Overview', 'Hidden Diagnostics')):
            page = report / 'definition/pages' / f'Page{page_index + 1}'
            page_json = {'$schema': SCHEMA + 'definition/page/2.1.0/schema.json',
                         'name': page.name, 'displayName': page_name, 'displayOption': 'FitToPage',
                         'height': 2160, 'width': 1280}
            if page_index:
                page_json['visibility'] = 'HiddenInViewMode'
            _write(page / 'page.json', page_json)
            for visual_index in range(40):
                projections = [_projection('Revenue')]
                if visual_index == 0:
                    projections.append(_projection('Month Label', 'Column'))
                    if report_index == 0:
                        projections.append(_projection('Revenue vs Target'))
                visual = {'$schema': SCHEMA + 'definition/visualContainer/2.9.0/schema.json',
                          'name': f'Visual{visual_index + 1:02d}', 'isHidden': bool(visual_index % 2),
                          'position': {'x': (visual_index % 4) * 300, 'y': (visual_index // 4) * 200,
                                       'z': visual_index, 'width': 290, 'height': 190},
                          'visual': {'visualType': 'tableEx', 'query': {'queryState': {
                              'Values': {'projections': projections}}}}}
                if report_index == page_index == visual_index == 0:
                    projections.append(_projection('Missing Report Metric'))
                    visual['visual']['objects'] = {'labels': [
                        {'properties': {}, 'selector': {'metadata': 'Sales.Obsolete Revenue'}}]}
                _write(page / 'visuals' / visual['name'] / 'visual.json', visual)
    _write(output / REPORTS[0] / 'definition/reportExtensions.json', {
        '$schema': SCHEMA + 'definition/reportExtension/1.0.0/schema.json', 'name': 'extension',
        'entities': [{'name': 'Sales', 'measures': [
            {'name': 'Report Target', 'dataType': 'Double', 'expression': '100', 'formatString': '#,0.00'},
            {'name': 'Revenue vs Target', 'dataType': 'Double',
             'expression': '[Revenue] - [Report Target]', 'formatString': '#,0.00'},
        ]}],
    })
    return {'root': output.resolve(), 'model': model.resolve(),
            'reports': [(output / name).resolve() for name in REPORTS]}


def describe_fixture(fixture):
    from semantic_model_cleaner import analyzer, metadata_validation, report_writer, webapp
    result = analyzer.analyze(fixture['root'], model_paths=[fixture['model']], report_paths=fixture['reports'])
    schema = metadata_validation.validate_report_paths(fixture['reports'], workspace=fixture['root'])
    if not result['coverage']['complete'] or not schema['ok']:
        raise ValueError('Generated fixture failed analyzer coverage or declared PBIR schema validation.')
    payload = webapp._serialize_results(result, model_paths=[str(fixture['model'])])
    revenue = next(row for row in result['items'] if row['item'].key == ('Sales', 'Revenue'))
    options = dict(model_path=fixture['model'], report_path=fixture['reports'][0],
                   entity_name='Sales', measure_name='Revenue vs Target', dry_run=True)
    blocked = report_writer.migrate_measure_to_model(**options)
    included = report_writer.migrate_measure_to_model(**options, include_dependencies=True)
    if blocked.get('ok') or not included.get('ok'):
        raise ValueError('Generated fixture did not preserve the required promotion dependency guard.')
    return {'root': str(fixture['root']), 'model': str(fixture['model']),
            'reports': list(map(str, fixture['reports'])), 'summary': result['summary'],
            'schema_validation': {key: schema[key] for key in ('ok', 'complete', 'counts')},
            'sales_children': next(table['itemCount'] for table in payload['tables'] if table['name'] == 'Sales'),
            'recommendations': dict(Counter(item['deleteSafety'] for item in payload['items'])),
            'revenue_references': len(revenue['usages']),
            'revenue_visibility': dict(Counter(
                f'page_hidden={usage.page_hidden},visual_hidden={usage.visual_hidden}' for usage in revenue['usages'])),
            'report_issues': dict(Counter(issue['issueType'] for issue in result['report_issues'])),
            'promotion_without_dependencies': blocked,
            'promotion_with_dependencies': included}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('output', type=Path, help='New or empty output directory')
    args = parser.parse_args(argv)
    try:
        print(json.dumps({'ok': True, 'fixture': describe_fixture(generate_fixture(args.output))}, indent=2))
        return 0
    except (OSError, ValueError, RuntimeError) as exc:
        print(json.dumps({'ok': False, 'error': str(exc)}))
        return 2


if __name__ == '__main__':
    raise SystemExit(main())
